media: public/img

localization:
  default: en
  locales:
    - label: English
      code: en
    - label: Francais
      code: fr

settings:
  site:
    url: http://localhost:8080
    preview:
      defaultOpen: true

content:
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    localization:
      scheme: files
      locale:
        type: folder
        position: collection
        default: omit
    site:
      path: /blog/{slug}
    view:
      fields: [title, draft, date, locale]
    fields:
      - name: title
        label: Title
        type: string
        required: true
        preview:
          target: "h1"
          bind: text
      - { name: description, label: Description, type: string }
      - name: date
        label: Date
        type: date
        preview:
          target: ".post-metadata time"
          bind: text
          transform:
            - date: MMMM d, yyyy
      - { name: draft, label: Draft, type: boolean }
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
        preview:
          target: "#skip > p"
          bind: html

  - name: about
    label: About page
    type: file
    path: content/about/index.md
    localization:
      scheme: files
      locale:
        type: folder
        position: custom
        root: content
        default: omit
    site:
      path: /about/
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
      - name: body
        label: Body
        type: rich-text
        preview:
          target: '[data-pagescms-field="body"]'
          bind: html

  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code
